# version: "2"
services:
  forntend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: tfd-frontend
    ports:
      - 4000:4000
    networks:
      - tfd-production
  nest:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: tfd-nest
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
      - ./backend/.env:/app/.env
      - ./backend/upload:/app/upload
    networks:
      - tfd-production
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: tfd-nest-nginx
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 8080:8080
    networks:
      - tfd-production
  db:
    image: postgres:12
    container_name: tfd-nest-db
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql
    networks:
      - tfd-production
  redis:
    image: redis:5
    container_name: tfd-redis
    ports:
      - 6379:6379
    networks:
      - tfd-production
volumes:
  postgresdata:

networks:
  tfd-production:
    name: tfd-production
    external: true
