name: Deploy to DevOps Assignment
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 178.18.254.89
          username: root
          password: hD5H9Mf5kwci
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd /var/www/devops-deploy
            git pull
            git submodule init
            git submodule update
            nvm install 16
            nvm use 16
            docker-compose down
            docker-compose build
            docker-compose up -d